print('Podaj imię kota numer 1:')
catName1 = input()
print('Podaj imię kota numer 2:')
catName2 = input()
print('Podaj imię kota numer 3:')
catName3 = input()
print('Podaj imię kota numer 4:')
catName4 = input()
print('Podaj imię kota numer 5:')
catName5 = input()
print('Podaj imię kota numer 6:')
catName6 = input()
print('Oto imiona kotów:')
print(catName1 + ' ' + catName2 + ' ' + catName3 + ' ' + catName4 + ' ' + catName5 + ' ' 
+ catName6)
